### ISSUE TITLE
j2ObjC_source.h issue still happening

### ISSUE THREAD

**Issue by conky2** [lukhnos/LuceneSearchDemo-iOS#4]
This issue is still happening despite a lot of effort to find a workaround.  I posted here as well: https://github.com/lukhnos/LuceneSearchDemo-iOS/issues/3

I very much appreciate your help -- I've been trying to get this up and running for the past week and can't get past this seemingly simple issue.

**Comment by lukhnos** [comment]
Strange. I had no problem building the app from a cleanly cloned git repo. Here's what I did:

```
git clone https://github.com/lukhnos/LuceneSearchDemo-iOS.git
cd LuceneSearchDemo-iOS
git submodule update --init --recursive
./setup-j2objc.sh
open LuceneSearchDemo.xcodeproj
```

I'm using Xcode 8.2.1, and naturally Xcode asked me to upgrade the Swift syntax, and I just let Xcode do its thing. I then switched the build target to iPhone 6 (pictured; any simulator should do) and click on the Run button. Everything built fine and the app did run in the Simulator.

![screen shot 2017-01-11 at 8 24 56 pm](https://cloud.githubusercontent.com/assets/25210/21876954/5021751c-d83c-11e6-8d8c-b5cdb2c76a1c.png)
