### ISSUE TITLE
org.apache.lucene.codecs.lucene53.Lucene53Codec does not exist

### ISSUE THREAD

**Issue by rajamobiletech** [lukhnos/LuceneSearchDemo-iOS#6]
I got error like this,

2020-02-11 15:23:23.979982+0530 IndexBookDemo[29801:6177360] *** Terminating app due to uncaught exception 'JavaUtilServiceConfigurationError', reason: 'An SPI class of type org.apache.lucene.codecs.Codec with classname org.apache.lucene.codecs.lucene53.Lucene53Codec does not exist.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   IndexBookDemo                       0x0000000101d46fde -[OrgApacheLuceneUtilSPIClassIterator next] + 846
	3   IndexBookDemo                       0x0000000101ccb8c9 -[OrgApacheLuceneUtilNamedSPILoader reloadWithJavaLangClassLoader:] + 169
	4   IndexBookDemo                       0x0000000101ccb80b OrgApacheLuceneUtilNamedSPILoader_initWithIOSClass_withJavaLangClassLoader_ + 235
	5   IndexBookDemo                       0x0000000101ccb6d3 OrgApacheLuceneUtilNamedSPILoader_initWithIOSClass_ + 115
	6   IndexBookDemo                       0x0000000101ccc0f1 new_OrgApacheLuceneUtilNamedSPILoader_initWithIOSClass_ + 49
	7   IndexBookDemo                       0x0000000101d2a719 +[OrgApacheLuceneCodecsCodec_Holder initialize] + 73
	8   libobjc.A.dylib                     0x00007fff513fc103 CALLING_SOME_+initialize_METHOD + 17
	9   libobjc.A.dylib                     0x00007fff513fcee9 initializeNonMetaClass + 624
	10  libobjc.A.dylib                     0x00007fff513fd4ba _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 157
	11  libobjc.A.dylib                     0x00007fff51407a5d lookUpImpOrForward + 595
	12  libobjc.A.dylib                     0x00007fff513f8219 _objc_msgSend_uncached + 73
	13  IndexBookDemo                       0x0000000101d2a54a OrgApacheLuceneCodecsCodec_getDefault + 58
	14  IndexBookDemo                       0x0000000101d222fe OrgApacheLuceneIndexLiveIndexWriterConfig_initWithOrgApacheLuceneAnalysisAnalyzer_ + 926
	15  IndexBookDemo                       0x0000000101c2b728 OrgApacheLuceneIndexIndexWriterConfig_initWithOrgApacheLuceneAnalysisAnalyzer_ + 40
	16  IndexBookDemo                       0x0000000101c2c7e1 new_OrgApacheLuceneIndexIndexWriterConfig_initWithOrgApacheLuceneAnalysisAnalyzer_ + 49
	17  IndexBookDemo                       0x0000000101920673 OrgLukhnosLucenestudyIndexer_initWithNSString_withBoolean_ + 227
	18  IndexBookDemo                       0x00000001019204d2 OrgLukhnosLucenestudyIndexer_initWithNSString_ + 82
	19  IndexBookDemo                       0x00000001019220b4 new_OrgLukhnosLucenestudyIndexer_initWithNSString_ + 68
	20  IndexBookDemo                       0x00000001019260c1 +[Document rebuildIndex] + 1441
	21  IndexBookDemo                       0x000000010192628b __25+[Document rebuildIndex:]_block_invoke + 43
	22  libdispatch.dylib                   0x0000000102d40dd4 _dispatch_call_block_and_release + 12
	23  libdispatch.dylib                   0x0000000102d41d48 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x0000000102d441ef _dispatch_queue_override_invoke + 1022
	25  libdispatch.dylib                   0x0000000102d5328c _dispatch_root_queue_drain + 351
	26  libdispatch.dylib                   0x0000000102d53b96 _dispatch_worker_thread2 + 132
	27  libsystem_pthread.dylib             0x00007fff524636b6 _pthread_wqthread + 220
	28  libsystem_pthread.dylib             0x00007fff52462827 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type JavaUtilServiceConfigurationError

Please help to fix this.

**Comment by lukhnos** [comment]
It's been a long time since I last worked on this experimental project, so please consider the project no longer maintained.

It seems that you hit this line: https://github.com/lukhnos/mobilelucene/blob/master/lucene/core/src/java/org/apache/lucene/util/SPIClassIterator.java#L263

And the problem is that the transpiled Lucene53Codec class was not found in your iOS binary. One common cause is that you didn't specify the `-ObjC` linker flag. The transpiled classes are usually not considered by the linker unless your native code explicitly makes reference to them. The `-ObjC` flag will force the linker to include all Objective-C classes: https://developer.apple.com/library/archive/qa/qa1490/_index.html ; the flag is present in the iOS sample app's Xcode project: https://github.com/lukhnos/LuceneSearchDemo-iOS/blob/master/LuceneSearchDemo.xcodeproj/project.pbxproj#L617
